dbt_dskola_project:
  outputs:
    dev:
      dbname: db_dskola
      host: localhost
      pass: '12345678'
      port: 5434
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
